export const categories = [
    "Reconnaissance",
    "Exploitation",
    "Web Application Security",
    "Password Cracking",
    "Brute Force",
    "Cloud Security",
    "CMS Security",
    "Wireless Attacks",
    "Post Exploitation",
    "Network Security",
    // "Forensics & Incident Response",
    "Social Engineering",
    "Blue Team / SOC Tools",
    // "Binary Analysis / Reverse Engineering",
    "Command Line Essentials"
];

  
export const topTools = [
  {
    name: "Nmap",
    slug: "nmap",
    description: "Network discovery and port scanning tool.",
    categories: ["Network Security", "Penetration Testing"],
    tag: "#Network",
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
  },
  {
    name: "Metasploit",
    slug: "metasploit",
    description: "Framework for developing and executing exploits.",
    categories: ["Penetration Testing", "Exploitation"],
    tag: "#Exploitation",
    bgColor: "bg-red-100",
    textColor: "text-red-800",
  },
  {
    name: "Gobuster",
    slug: "gobuster",
    description: "Directory and file brute-forcing tool.",
    categories: ["Web Application Security", "Penetration Testing"],
    tag: "#Web",
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-800",
  },
  {
    name: "Hydra",
    slug: "hydra",
    description: "Login cracker for multiple protocols.",
    categories: ["Brute Force", "Network Security"],
    tag: "#BruteForce",
    bgColor: "bg-purple-100",
    textColor: "text-purple-800",
  },
  {
    name: "Burp Suite",
    slug: "burpsuite",
    description: "Web vulnerability scanner and proxy.",
    categories: ["Web Application Security", "Penetration Testing"],
    tag: "#Web",
    bgColor: "bg-orange-100",
    textColor: "text-orange-800",
  },
  {
    name: "John the Ripper",
    slug: "john-the-ripper",
    description: "Popular password cracking tool.",
    categories: ["Password Cracking", "Forensics"],
    tag: "#Cracking",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
  },
  {
    name: "WPScan",
    slug: "wpscan",
    description: "WordPress vulnerability scanner.",
    categories: ["Web Application Security", "CMS Security"],
    tag: "#CMS",
    bgColor: "bg-pink-100",
    textColor: "text-pink-800",
  },
  {
    name: "SQLMap",
    slug: "sqlmap",
    description: "Automated SQL injection and database takeover tool.",
    categories: ["Database Security", "Web Application Security"],
    tag: "#Database",
    bgColor: "bg-indigo-100",
    textColor: "text-indigo-800",
  },
  {
    name: "Nikto",
    slug: "nikto",
    description: "Web server scanner for detecting vulnerabilities and misconfigurations.",
    categories: ["Web Application Security", "Reconnaissance"],
    tag: "#Web",
    bgColor: "bg-lime-100",
    textColor: "text-lime-800",
  },
  {
    name: "ffuf",
    slug: "ffuf",
    description: "Fast web fuzzer for discovering hidden directories, files, and parameters.",
    categories: ["Web Application Security", "Brute Force"],
    tag: "#Web",
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-800",
  }    
];

  
export const allTools = [
    // Reconnaissance
    {
      name: "Nmap",
      slug: "nmap",
      description: "Network scanner for discovering hosts, ports, and services.",
      categories: ["Reconnaissance", "Network Security"],
      tag: "#NetworkScanning",
      bgColor: "bg-blue-100",
      textColor: "text-blue-800",
    },
    {
      name: "Netcat",
      slug: "netcat",
      description: "Versatile tool for port scanning and network data transfer.",
      categories: ["Reconnaissance", "Network Security"],
      tag: "#Networking",
      bgColor: "bg-gray-100",
      textColor: "text-gray-800",
    },
    {
      name: "Masscan",
      slug: "masscan",
      description: "High-speed port scanner for large-scale network recon.",
      categories: ["Reconnaissance", "Network Security"],
      tag: "#PortScanning",
      bgColor: "bg-blue-200",
      textColor: "text-blue-900",
    },
    {
      name: "Recon-ng",
      slug: "recon-ng",
      description: "Framework for open-source intelligence and reconnaissance.",
      categories: ["Reconnaissance", "OSINT"],
      tag: "#OSINT",
      bgColor: "bg-purple-100",
      textColor: "text-purple-800",
    },
    {
      name: "Maltego",
      slug: "maltego",
      description: "OSINT tool for visualizing entity relationships.",
      categories: ["Reconnaissance", "OSINT"],
      tag: "#DataVisualization",
      bgColor: "bg-teal-100",
      textColor: "text-teal-800",
    },
    {
      name: "theHarvester",
      slug: "theharvester",
      description: "Gathers emails and subdomains from public sources.",
      categories: ["Reconnaissance", "OSINT"],
      tag: "#OSINT",
      bgColor: "bg-purple-200",
      textColor: "text-purple-900",
    },
    {
      name: "Shodan",
      slug: "shodan",
      description: "Search engine for Internet-connected devices, useful for reconnaissance and OSINT.",
      categories: ["Reconnaissance", "OSINT"],
      tag: "#Recon",
      bgColor: "bg-indigo-100",
      textColor: "text-indigo-800",
    },
    {
      name: "Amass",
      slug: "amass",
      description: "Tool for DNS enumeration and network mapping.",
      categories: ["Reconnaissance", "Network Security"],
      tag: "#DNS",
      bgColor: "bg-blue-300",
      textColor: "text-blue-900",
    },
    {
      name: "Sublist3r",
      slug: "sublist3r",
      description: "Fast subdomain enumeration tool.",
      categories: ["Reconnaissance", "OSINT"],
      tag: "#SubdomainEnumeration",
      bgColor: "bg-purple-300",
      textColor: "text-purple-900",
    },   
    {
      name: "DNSEnum",
      slug: "dnsenum",
      description: "Perl-based DNS enumeration tool for discovering subdomains, hosts, and DNS records.",
      categories: ["Reconnaissance"],
      tag: "#DNS",
      bgColor: "bg-yellow-100",
      textColor: "text-yellow-800",
    },
 
  
    // Exploitation
    {
      name: "Metasploit",
      slug: "metasploit",
      description: "Penetration testing platform for exploiting vulnerabilities.",
      categories: ["Exploitation", "Penetration Testing"],
      tag: "#Exploitation",
      bgColor: "bg-red-100",
      textColor: "text-red-800",
    },
    {
      name: "Empire",
      slug: "empire",
      description: "Framework for exploitation and post-exploitation tasks.",
      categories: ["Exploitation", "Post Exploitation"],
      tag: "#PostExploitation",
      bgColor: "bg-red-300",
      textColor: "text-red-900",
    },
    {
      name: "Impacket",
      slug: "impacket",
      description: "Collection of Python scripts for network protocol exploitation, lateral movement, and credential dumping.",
      categories: ["Post Exploitation", "Active Directory", "Credential Access"],
      tag: "#PostExploitation",
      bgColor: "bg-purple-200",
      textColor: "text-purple-900"
    },    
    {
      name: "File Inclusion",
      slug: "file-inclusion",
      description: "A vulnerability that allows attackers to include files on a server through the web browser. Common types include LFI (Local File Inclusion) and RFI (Remote File Inclusion).",
      categories: ["Exploitation", "Web Application Security"],
      tag: "#FileInclusion",
      bgColor: "bg-yellow-200",
      textColor: "text-yellow-800"
    },
  
    // Web Application Security
    {
      name: "Burp Suite",
      slug: "burpsuite",
      description: "Web vulnerability scanner and proxy for testing apps.",
      categories: ["Web Application Security", "Brute Force"],
      tag: "#WebSecurity",
      bgColor: "bg-green-100",
      textColor: "text-green-800",
    },
    {
      name: "SQLmap",
      slug: "sqlmap",
      description: "Automated tool for SQL injection and database takeover.",
      categories: ["Web Application Security", "Exploitation"],
      tag: "#SQLInjection",
      bgColor: "bg-green-200",
      textColor: "text-green-900",
    },
    {
      name: "OWASP ZAP",
      slug: "owasp-zap",
      description: "Web app scanner for XSS and other vulnerabilities.",
      categories: ["Web Application Security", "Vulnerability Assessment"],
      tag: "#WebScanning",
      bgColor: "bg-green-300",
      textColor: "text-green-900",
    },
    {
      name: "Nikto",
      slug: "nikto",
      description: "Web server scanner for misconfigurations.",
      categories: ["Web Application Security", "Vulnerability Assessment"],
      tag: "#WebScanning",
      bgColor: "bg-green-100",
      textColor: "text-green-800",
    },
  
    // Password Cracking
    {
      name: "John the Ripper",
      slug: "john-the-ripper",
      description: "Password cracker for various hash types.",
      categories: ["Password Cracking", "Penetration Testing"],
      tag: "#PasswordCracking",
      bgColor: "bg-purple-100",
      textColor: "text-purple-800",
    },
    {
      name: "Hashcat",
      slug: "hashcat",
      description: "GPU-accelerated password cracker for complex hashes.",
      categories: ["Password Cracking", "Penetration Testing"],
      tag: "#PasswordCracking",
      bgColor: "bg-purple-200",
      textColor: "text-purple-900",
    },
    {
      name: "RainbowCrack",
      slug: "rainbowcrack",
      description: "Password cracker using precomputed rainbow tables.",
      categories: ["Password Cracking", "Penetration Testing"],
      tag: "#PasswordCracking",
      bgColor: "bg-purple-300",
      textColor: "text-purple-900",
    },
  
    // Brute Force
    {
      name: "Hydra",
      slug: "hydra",
      description: "Brute-forces credentials for network services.",
      categories: ["Brute Force", "Password Cracking"],
      tag: "#BruteForce",
      bgColor: "bg-yellow-100",
      textColor: "text-yellow-800",
    },
    {
      name: "Medusa",
      slug: "medusa",
      description: "Parallel brute-forcing tool for multiple protocols.",
      categories: ["Brute Force", "Password Cracking"],
      tag: "#BruteForce",
      bgColor: "bg-yellow-200",
      textColor: "text-yellow-900",
    },
    // {
    //   name: "Patator",
    //   slug: "patator",
    //   description: "Modular brute-forcing tool for various services.",
    //   categories: ["Brute Force", "Password Cracking"],
    //   tag: "#BruteForce",
    //   bgColor: "bg-yellow-300",
    //   textColor: "text-yellow-900",
    // },
    {
      name: "Gobuster",
      slug: "gobuster",
      description: "Directory and file brute-forcing tool.",
      categories: ["Web Application Security", "Brute Force"],
      tag: "#Web",
      bgColor: "bg-yellow-100",
      textColor: "text-yellow-800",
    },
    {
      name: "ffuf",
      slug: "ffuf",
      description: "Fast web fuzzer for discovering hidden directories, files, and parameters.",
      categories: ["Web Application Security", "Brute Force"],
      tag: "#Web",
      bgColor: "bg-yellow-100",
      textColor: "text-yellow-800",
    }, 
  
    // Wireless Attacks
    {
      name: "Aircrack-ng",
      slug: "aircrack-ng",
      description: "Suite for auditing and cracking Wi-Fi networks.",
      categories: ["Wireless Attacks", "Penetration Testing"],
      tag: "#WiFiHacking",
      bgColor: "bg-indigo-100",
      textColor: "text-indigo-800",
    },
    {
      name: "Kismet",
      slug: "kismet",
      description: "Wireless network detector and sniffer.",
      categories: ["Wireless Attacks", "Network Security"],
      tag: "#WirelessScanning",
      bgColor: "bg-indigo-200",
      textColor: "text-indigo-900",
    },
    {
      name: "Reaver",
      slug: "reaver",
      description: "Attacks WPS-enabled Wi-Fi routers for key recovery.",
      categories: ["Wireless Attacks", "Penetration Testing"],
      tag: "#WiFiHacking",
      bgColor: "bg-indigo-300",
      textColor: "text-indigo-900",
    },
    {
      name: "Bettercap",
      slug: "bettercap",
      description: "Powerful, flexible, and portable tool for network attacks, monitoring, and man-in-the-middle (MITM) activities.",
      categories: ["Network Security", "Wireless Attacks", "Man-in-the-Middle"],
      tag: "#Network",
      bgColor: "bg-yellow-100",
      textColor: "text-yellow-800"
    },    
  
    // Post Exploitation
    {
      name: "Mimikatz",
      slug: "mimikatz",
      description: "Extracts credentials and hashes from Windows memory.",
      categories: ["Post Exploitation", "Penetration Testing"],
      tag: "#CredentialDumping",
      bgColor: "bg-pink-100",
      textColor: "text-pink-800",
    },
    {
      name: "PowerSploit",
      slug: "powersploit",
      description: "PowerShell scripts for privilege escalation.",
      categories: ["Post Exploitation", "Penetration Testing"],
      tag: "#PostExploitation",
      bgColor: "bg-pink-200",
      textColor: "text-pink-900",
    },
    {
      name: "Responder",
      slug: "responder",
      description: "Captures NTLM hashes via network poisoning.",
      categories: ["Post Exploitation", "Network Security"],
      tag: "#HashCapture",
      bgColor: "bg-pink-300",
      textColor: "text-pink-900",
    },
  
    // CMS Security
    {
      name: "WPScan",
      slug: "wpscan",
      description: "WordPress scanner for plugins and vulnerabilities.",
      categories: ["CMS Security", "Web Application Security"],
      tag: "#CMSScanning",
      bgColor: "bg-teal-100",
      textColor: "text-teal-800",
    },
    {
      name: "JoomScan",
      slug: "joomscan",
      description: "Joomla CMS scanner for vulnerabilities.",
      categories: ["CMS Security", "Web Application Security"],
      tag: "#CMSScanning",
      bgColor: "bg-teal-200",
      textColor: "text-teal-900",
    },
    {
      name: "Droopescan",
      slug: "droopescan",
      description: "Drupal CMS scanner for vulnerabilities.",
      categories: ["CMS Security", "Web Application Security"],
      tag: "#CMSScanning",
      bgColor: "bg-teal-300",
      textColor: "text-teal-900",
    },
  
    // Network Security / Traffic Analysis
    {
      name: "Wireshark",
      slug: "wireshark",
      description: "Network protocol analyzer for traffic inspection.",
      categories: ["Network Security", "Traffic Analysis"],
      tag: "#PacketAnalysis",
      bgColor: "bg-cyan-100",
      textColor: "text-cyan-800",
    },
    {
      name: "Tcpdump",
      slug: "tcpdump",
      description: "Command-line packet analyzer for network traffic.",
      categories: ["Network Security", "Traffic Analysis"],
      tag: "#PacketCapture",
      bgColor: "bg-cyan-200",
      textColor: "text-cyan-900",
    },
    {
      name: "Zeek",
      slug: "zeek",
      description: "Network monitoring tool for security and logging.",
      categories: ["Network Security", "Traffic Analysis"],
      tag: "#NetworkMonitoring",
      bgColor: "bg-cyan-300",
      textColor: "text-cyan-900",
    },
  
    // Forensics & Incident Response
    {
      name: "Autopsy",
      slug: "autopsy",
      description: "GUI-based platform for digital forensics analysis.",
      categories: ["Forensics & Incident Response"],
      tag: "#Forensics",
      bgColor: "bg-gray-200",
      textColor: "text-gray-900",
    },
    {
      name: "FTK Imager",
      slug: "ftk-imager",
      description: "Tool for creating and analyzing forensic disk images.",
      categories: ["Forensics & Incident Response"],
      tag: "#DiskImaging",
      bgColor: "bg-gray-300",
      textColor: "text-gray-900",
    },
    {
      name: "Volatility",
      slug: "volatility",
      description: "Memory forensics framework for analyzing RAM dumps.",
      categories: ["Forensics & Incident Response"],
      tag: "#MemoryForensics",
      bgColor: "bg-gray-100",
      textColor: "text-gray-800",
    },
  
    // Social Engineering
    {
      name: "SET",
      slug: "set",
      description: "Social engineering toolkit for phishing and credential harvesting.",
      categories: ["Social Engineering", "Exploitation"],
      tag: "#SocialEngineering",
      bgColor: "bg-orange-200",
      textColor: "text-orange-900",
    },
    {
      name: "PhishX",
      slug: "phishx",
      description: "Tool for creating and managing phishing campaigns.",
      categories: ["Social Engineering"],
      tag: "#Phishing",
      bgColor: "bg-orange-300",
      textColor: "text-orange-900",
    },
    {
      name: "Evilginx2",
      slug: "evilginx2",
      description: "Framework for man-in-the-middle phishing attacks.",
      categories: ["Social Engineering", "Exploitation"],
      tag: "#Phishing",
      bgColor: "bg-orange-100",
      textColor: "text-orange-800",
    },
  
    // Blue Team / SOC Tools
    {
      name: "Snort",
      slug: "snort",
      description: "Open-source intrusion detection and prevention system.",
      categories: ["Blue Team / SOC Tools", "Network Security"],
      tag: "#IDS",
      bgColor: "bg-blue-300",
      textColor: "text-blue-900",
    },
    {
      name: "Suricata",
      slug: "suricata",
      description: "High-performance IDS/IPS and network monitoring engine.",
      categories: ["Blue Team / SOC Tools", "Network Security"],
      tag: "#IDS",
      bgColor: "bg-blue-400",
      textColor: "text-blue-900",
    },
    {
      name: "OSSEC",
      slug: "ossec",
      description: "Host-based intrusion detection system for log analysis.",
      categories: ["Blue Team / SOC Tools"],
      tag: "#HIDS",
      bgColor: "bg-blue-200",
      textColor: "text-blue-900",
    },
  
    // Cloud Security
    {
      name: "ScoutSuite",
      slug: "scoutsuite",
      description: "Multi-cloud security auditing tool for AWS, Azure, GCP.",
      categories: ["Cloud Security"],
      tag: "#CloudAuditing",
      bgColor: "bg-sky-100",
      textColor: "text-sky-800",
    },
    {
      name: "Prowler",
      slug: "prowler",
      description: "Security assessment tool for AWS environments.",
      categories: ["Cloud Security"],
      tag: "#CloudSecurity",
      bgColor: "bg-sky-200",
      textColor: "text-sky-900",
    },
    {
      name: "Pacu",
      slug: "pacu",
      description: "AWS exploitation framework for penetration testing.",
      categories: ["Cloud Security", "Exploitation"],
      tag: "#CloudExploitation",
      bgColor: "bg-sky-300",
      textColor: "text-sky-900",
    },
    {
      "name": "AWS CLI",
      "slug": "aws-cli",
      "description": "A unified tool to manage AWS services from the command line. It enables users to script, automate, and control cloud resources efficiently.",
      "categories": ["Cloud Security"],
      "tag": "#AWSCLI",
      "bgColor": "bg-blue-200",
      "textColor": "text-blue-800"
    },    
  
    // Binary Analysis / Reverse Engineering
    {
      name: "Ghidra",
      slug: "ghidra",
      description: "Open-source reverse engineering tool for binary analysis.",
      categories: ["Binary Analysis / Reverse Engineering"],
      tag: "#ReverseEngineering",
      bgColor: "bg-amber-100",
      textColor: "text-amber-800",
    },
    {
      name: "Radare2",
      slug: "radare2",
      description: "Framework for reverse engineering and binary analysis.",
      categories: ["Binary Analysis / Reverse Engineering"],
      tag: "#BinaryAnalysis",
      bgColor: "bg-amber-200",
      textColor: "text-amber-900",
    },
    {
      name: "Binwalk",
      slug: "binwalk",
      description: "Tool for analyzing and extracting firmware images.",
      categories: ["Binary Analysis / Reverse Engineering"],
      tag: "#FirmwareAnalysis",
      bgColor: "bg-amber-300",
      textColor: "text-amber-900",
    },
    // Command Line Essentials
    {
      name: "Linux",
      slug: "linux",
      description: "Open-source operating system used in most cybersecurity environments for development, testing, and deployment.",
      categories: ["Command Line Essentials", "Operating Systems"],
      tag: "#Linux",
      bgColor: "bg-gray-200",
      textColor: "text-gray-800",
    },    
    {
      "name": "SSH",
      "slug": "ssh",
      "description": "Secure Shell protocol for remote administration and encrypted communication.",
      "categories": ["Command Line Essentials"],
      "tag": "#CLI",
      "bgColor": "bg-gray-200",
      "textColor": "text-gray-900"
    },
    {
      "name": "Vim",
      "slug": "vim",
      "description": "Powerful terminal-based text editor for efficient file editing.",
      "categories": ["Command Line Essentials"],
      "tag": "#CLI",
      "bgColor": "bg-green-100",
      "textColor": "text-green-800"
    },
    {
      "name": "Tmux",
      "slug": "tmux",
      "description": "Terminal multiplexer for managing multiple sessions in one terminal window.",
      "categories": ["Command Line Essentials"],
      "tag": "#CLI",
      "bgColor": "bg-yellow-100",
      "textColor": "text-yellow-800"
    },
    {
      "name": "cURL",
      "slug": "curl",
      "description": "Command-line tool for transferring data with URL syntax — supports HTTP, HTTPS, FTP, and more.",
      "categories": ["Command Line Essentials"],
      "tag": "#CLI",
      "bgColor": "bg-blue-100",
      "textColor": "text-blue-800"
    },
    {
      "name": "Bash",
      "slug": "bash",
      "description": "Popular Unix shell and scripting language used for automation and system tasks.",
      "categories": ["Command Line Essentials"],
      "tag": "#CLI",
      "bgColor": "bg-indigo-100",
      "textColor": "text-indigo-800"
    },          
    {
      name: "htop",
      slug: "htop",
      description: "Interactive process viewer for Unix systems, offering a real-time, color-coded display of system processes, CPU, memory, and swap usage.",
      categories: ["Operating System", "System Monitoring"],
      tag: "#Linux",
      bgColor: "bg-green-200",
      textColor: "text-green-900",
    }
                
];